
const items = [
            {
              "code": "754aedd0-ee70-40da-b02a-41f5f0d643a3",
              "price": 19,
              "imageUrl": "https://irisv4sandboxasstore.blob.core.windows.net/fileresources/public/iris/heddon/hhr/chiliandricef9300da6b1dd417fa4ed74fe60e3be58.jpg",
              "directContentParameter": null,
              "type": "Product",
              "name": "Chilli Con Carne",
              "shortDescription": null,
              "longDescription": "<p>Chilli con carne served with fluffy basmati rice and sour cream</p>\r\n",
              "categoryCode": "571d0cbd-fc66-481f-bcd0-2f9e928e78c0",
              "itemCode": "dfd6acb3-b6d9-4c4e-b562-79f61b562caf",
              "printEnabled": false,
              "emailSharingEnable": false,
              "qrCodeEnabled": false,
              "promo": false,
              "directContentType": null,
              "availabilityPeriod": null,
              "attributes": [],
              "availabilityPeriods": [],
              "relatedCategoryItemCodes": [],
              "modifiers": [],
              "analyticsTag": null,
              "templateTag": null,
              "buttons": []
            },
            {
              "code": "94f0faf3-0f88-4d87-a151-3d967135d767",
              "price": 15,
              "imageUrl": "https://irisv4sandboxasstore.blob.core.windows.net/fileresources/public/iris/heddon/hhr/hameggandchipsbffabeb3a09c4dc780d307cc764908a3.jpg",
              "directContentParameter": null,
              "type": "Product",
              "name": "Ham, Egg and chips with ketchup",
              "shortDescription": null,
              "longDescription": "<p>Local baked ham, fried egg and home-made chips</p>\r\n",
              "categoryCode": "571d0cbd-fc66-481f-bcd0-2f9e928e78c0",
              "itemCode": "9c1c6601-1b8a-4c8d-b4ce-754210d8ab76",
              "printEnabled": false,
              "emailSharingEnable": false,
              "qrCodeEnabled": false,
              "promo": false,
              "directContentType": null,
              "availabilityPeriod": null,
              "attributes": [],
              "availabilityPeriods": [],
              "relatedCategoryItemCodes": [],
              "modifiers": [],
              "analyticsTag": null,
              "templateTag": null,
              "buttons": []
            },
            {
              "code": "1418fa34-bb0d-4866-9a1f-6b11473dfc97",
              "price": 15,
              "imageUrl": "https://irisv4sandboxasstore.blob.core.windows.net/fileresources/public/iris/heddon/hhr/yorkshirepuddingandpotato21ab5f7ea27e45698310335ee4d31ad6.jpg",
              "directContentParameter": null,
              "type": "Product",
              "name": "Yorkshire Pudding and Potato",
              "shortDescription": null,
              "longDescription": "<p>Yorkshire pudding served with buttery mashed potato and peas</p>\r\n",
              "categoryCode": "571d0cbd-fc66-481f-bcd0-2f9e928e78c0",
              "itemCode": "7486551f-ad68-4068-9325-77d2da8ee8b4",
              "printEnabled": false,
              "emailSharingEnable": false,
              "qrCodeEnabled": false,
              "promo": false,
              "directContentType": null,
              "availabilityPeriod": null,
              "attributes": [],
              "availabilityPeriods": [],
              "relatedCategoryItemCodes": [],
              "modifiers": [],
              "analyticsTag": null,
              "templateTag": null,
              "buttons": []
            },
            {
              "code": "f5c6ee85-954e-403e-a05c-cfebc30ad22b",
              "price": 12,
              "imageUrl": "https://irisv4sandboxasstore.blob.core.windows.net/fileresources/public/iris/heddon/hhr/macaronicheese5ecfe7d025184906b8be4211abefa941.jpg",
              "directContentParameter": null,
              "type": "Product",
              "name": "Macaroni Cheese",
              "shortDescription": null,
              "longDescription": "<p>Classic macaroni cheese...pasta with a creamy cheese sauce and a crunchy topping</p>\r\n",
              "categoryCode": "571d0cbd-fc66-481f-bcd0-2f9e928e78c0",
              "itemCode": "9cff6629-e423-4dce-a87d-eb1deb7d3092",
              "printEnabled": false,
              "emailSharingEnable": false,
              "qrCodeEnabled": false,
              "promo": false,
              "directContentType": null,
              "availabilityPeriod": null,
              "attributes": [],
              "availabilityPeriods": [],
              "relatedCategoryItemCodes": [],
              "modifiers": [],
              "analyticsTag": null,
              "templateTag": null,
              "buttons": []
            },
            {
              "code": "98e163a9-ae08-4d26-bae6-7050f0059811",
              "price": 15,
              "imageUrl": "https://irisv4sandboxasstore.blob.core.windows.net/fileresources/public/iris/heddon/hhr/charcuiterieboarda6fa4bd13da3460888db5bc62fa6e09b.jpg",
              "directContentParameter": null,
              "type": "Product",
              "name": "Charcuterie Board",
              "shortDescription": null,
              "longDescription": "<p>A selection of cold meats, olives, fresh vegetables and lightly toasted bread</p>\r\n",
              "categoryCode": "571d0cbd-fc66-481f-bcd0-2f9e928e78c0",
              "itemCode": "290ad96f-2343-4666-a7e9-47aefdf61cf8",
              "printEnabled": false,
              "emailSharingEnable": false,
              "qrCodeEnabled": false,
              "promo": false,
              "directContentType": null,
              "availabilityPeriod": null,
              "attributes": [],
              "availabilityPeriods": [],
              "relatedCategoryItemCodes": [],
              "modifiers": [],
              "analyticsTag": null,
              "templateTag": null,
              "buttons": []
            },
            {
              "code": "23d99570-1ca7-48ad-b240-b8c6f83246b0",
              "price": 12,
              "imageUrl": "https://irisv4sandboxasstore.blob.core.windows.net/fileresources/public/iris/heddon/hhr/sardines5d53a651ca504e5ab4c408d64a4472fe.jpg",
              "directContentParameter": null,
              "type": "Product",
              "name": "Sardines",
              "shortDescription": null,
              "longDescription": "<p>Freshly grilled sardines served with a garlic mayonnaise</p>\r\n",
              "categoryCode": "571d0cbd-fc66-481f-bcd0-2f9e928e78c0",
              "itemCode": "a08e5f3e-88f2-40ae-a8ae-7ca9df0e1288",
              "printEnabled": false,
              "emailSharingEnable": false,
              "qrCodeEnabled": false,
              "promo": false,
              "directContentType": null,
              "availabilityPeriod": null,
              "attributes": [],
              "availabilityPeriods": [],
              "relatedCategoryItemCodes": [],
              "modifiers": [],
              "analyticsTag": null,
              "templateTag": null,
              "buttons": []
            },
            {
              "code": "1883c752-7f57-4fd6-a7e0-96bb27e04eb6",
              "price": 18,
              "imageUrl": "https://irisv4sandboxasstore.blob.core.windows.net/fileresources/public/iris/heddon/hhr/musselsec56fd11752743a4aad7f324c97255de.jpg",
              "directContentParameter": null,
              "type": "Product",
              "name": "Mussels",
              "shortDescription": null,
              "longDescription": "<p>Fresh juicy mussels cooked in a thai broth</p>\r\n",
              "categoryCode": "571d0cbd-fc66-481f-bcd0-2f9e928e78c0",
              "itemCode": "38641cf1-9807-48d1-bb8f-afe974137410",
              "printEnabled": false,
              "emailSharingEnable": false,
              "qrCodeEnabled": false,
              "promo": false,
              "directContentType": null,
              "availabilityPeriod": null,
              "attributes": [],
              "availabilityPeriods": [],
              "relatedCategoryItemCodes": [],
              "modifiers": [],
              "analyticsTag": null,
              "templateTag": null,
              "buttons": []
            },
            {
              "code": "6a7308ec-4da3-4e13-9f6a-49890f160fe4",
              "price": 15,
              "imageUrl": "https://irisv4sandboxasstore.blob.core.windows.net/fileresources/public/iris/heddon/hhr/pomegranatepastabbe59714174f472bacde091786bf53db.jpg",
              "directContentParameter": null,
              "type": "Product",
              "name": "Pomegranate Pasta",
              "shortDescription": null,
              "longDescription": "<p>Penne pasta with a pomegranate vinaigrette, bacon, tomatoes and pomegranate seeds</p>\r\n",
              "categoryCode": "571d0cbd-fc66-481f-bcd0-2f9e928e78c0",
              "itemCode": "8a34e0f3-16a6-428c-8da3-46d4bf0da757",
              "printEnabled": false,
              "emailSharingEnable": false,
              "qrCodeEnabled": false,
              "promo": false,
              "directContentType": null,
              "availabilityPeriod": null,
              "attributes": [],
              "availabilityPeriods": [],
              "relatedCategoryItemCodes": [],
              "modifiers": [],
              "analyticsTag": null,
              "templateTag": null,
              "buttons": []
            },
            {
              "code": "f8248500-e0a8-4f96-bf1a-43d36b2b7c11",
              "price": 15,
              "imageUrl": "https://irisv4sandboxasstore.blob.core.windows.net/fileresources/public/iris/heddon/hhr/musselspastaf4e0f22a42b44a5fa45bb594823eaebf.jpg",
              "directContentParameter": null,
              "type": "Product",
              "name": "Mussels Pasta",
              "shortDescription": null,
              "longDescription": "<p>Fresh plump mussels with pasta and a tangy tomato sauce</p>\r\n",
              "categoryCode": "571d0cbd-fc66-481f-bcd0-2f9e928e78c0",
              "itemCode": "79aa4669-1255-419b-a75a-60d5754d0830",
              "printEnabled": false,
              "emailSharingEnable": false,
              "qrCodeEnabled": false,
              "promo": false,
              "directContentType": null,
              "availabilityPeriod": null,
              "attributes": [],
              "availabilityPeriods": [],
              "relatedCategoryItemCodes": [],
              "modifiers": [],
              "analyticsTag": null,
              "templateTag": null,
              "buttons": []
            },
            {
              "code": "17a3a159-34d2-440d-8471-f98fcff40acb",
              "price": 21,
              "imageUrl": "https://irisv4sandboxasstore.blob.core.windows.net/fileresources/public/iris/heddon/hhr/12ozsirloinsteak66c0749d30574e25b564612f68e2a4d7.jpg",
              "directContentParameter": null,
              "type": "Product",
              "name": "12oz Sirloin Steak",
              "shortDescription": null,
              "longDescription": "<p>Succulent sirloin steak cooked how you like it. &nbsp;Served with handcut chips, roasted tomatoes and green salad</p>\r\n",
              "categoryCode": "571d0cbd-fc66-481f-bcd0-2f9e928e78c0",
              "itemCode": "ad99b575-a82c-4681-a0ce-1083b657126a",
              "printEnabled": false,
              "emailSharingEnable": false,
              "qrCodeEnabled": false,
              "promo": false,
              "directContentType": null,
              "availabilityPeriod": null,
              "attributes": [],
              "availabilityPeriods": [],
              "relatedCategoryItemCodes": [],
              "modifiers": [],
              "analyticsTag": null,
              "templateTag": null,
              "buttons": []
            },
            {
              "code": "5c6f4c61-de5e-4533-853a-cf28f67fd378",
              "price": 15,
              "imageUrl": "https://irisv4sandboxasstore.blob.core.windows.net/fileresources/public/iris/heddon/hhr/fallafel722ae48cf92d445a8b1936e989c5c7f8.jpg",
              "directContentParameter": null,
              "type": "Product",
              "name": "Falafel",
              "shortDescription": null,
              "longDescription": "<p>Heddon-made falafel with a fresh green salad</p>\r\n",
              "categoryCode": "571d0cbd-fc66-481f-bcd0-2f9e928e78c0",
              "itemCode": "1a8537e9-9c36-4008-97b5-602a82e3b78f",
              "printEnabled": false,
              "emailSharingEnable": false,
              "qrCodeEnabled": false,
              "promo": false,
              "directContentType": null,
              "availabilityPeriod": null,
              "attributes": [],
              "availabilityPeriods": [],
              "relatedCategoryItemCodes": [],
              "modifiers": [],
              "analyticsTag": null,
              "templateTag": null,
              "buttons": []
            },
            {
              "code": "b93940b0-b68f-444d-a8c8-b9308c3b4526",
              "price": 21,
              "imageUrl": "https://irisv4sandboxasstore.blob.core.windows.net/fileresources/public/iris/heddon/hhr/flatironsteaked8fce956c344d94b6d3685f1735f124.jpg",
              "directContentParameter": null,
              "type": "Product",
              "name": "Flat Iron Steak",
              "shortDescription": null,
              "longDescription": "<p>Seared flat iron steak served with roasted tomatoes, green salad and hand-cut chips</p>\r\n",
              "categoryCode": "571d0cbd-fc66-481f-bcd0-2f9e928e78c0",
              "itemCode": "055a1ed2-70b0-4584-b63d-c9b4ce6ab6ad",
              "printEnabled": false,
              "emailSharingEnable": false,
              "qrCodeEnabled": false,
              "promo": false,
              "directContentType": null,
              "availabilityPeriod": null,
              "attributes": [],
              "availabilityPeriods": [],
              "relatedCategoryItemCodes": [],
              "modifiers": [
                {
                  "name": "How would you like your steak cooked? (Copy)",
                  "code": "3039ae25-277c-41b6-a550-67c552a5b3f7",
                  "parentModifierOptionCode": null,
                  "type": "select",
                  "isRequired": true,
                  "modifierOptions": [
                    {
                      "value": "rare",
                      "code": "b8aef073-401d-49ff-a6f7-3000ba69326a",
                      "price": 0,
                      "modifierOptionCode": "3039ae25-277c-41b6-a550-67c552a5b3f7",
                      "subModifiers": [],
                      "timeValue": 0,
                      "name": "Rare",
                      "optionType": "Text"
                    },
                    {
                      "value": "medium-rare",
                      "code": "7fa8e9fe-1c4f-4b77-85db-822e5abbdb31",
                      "price": 0,
                      "modifierOptionCode": "3039ae25-277c-41b6-a550-67c552a5b3f7",
                      "subModifiers": [],
                      "timeValue": 0,
                      "name": "Medium Rare",
                      "optionType": "Text"
                    },
                    {
                      "value": "medium",
                      "code": "85ed20f3-ec53-49d7-bb15-8598e6f205cf",
                      "price": 0,
                      "modifierOptionCode": "3039ae25-277c-41b6-a550-67c552a5b3f7",
                      "subModifiers": [],
                      "timeValue": 0,
                      "name": "Medium",
                      "optionType": "Text"
                    },
                    {
                      "value": "well-done",
                      "code": "e8c1661d-18be-40e8-a7f1-8d68c4a03f7c",
                      "price": 0,
                      "modifierOptionCode": "3039ae25-277c-41b6-a550-67c552a5b3f7",
                      "subModifiers": [],
                      "timeValue": 0,
                      "name": "Well Done",
                      "optionType": "Text"
                    }
                  ]
                }
              ],
              "analyticsTag": null,
              "templateTag": null,
              "buttons": []
            },
            {
              "code": "870896dd-382a-4d6f-a9b0-634ab1c26cf7",
              "price": 19,
              "imageUrl": "https://irisv4sandboxasstore.blob.core.windows.net/fileresources/public/iris/heddon/hhr/fishandchips1ab65d7e70764e7d9ca7311c06f51208.jpg",
              "directContentParameter": null,
              "type": "Product",
              "name": "Fish & Chips",
              "shortDescription": null,
              "longDescription": "<p>Fresh cod in a light batte served with hand-cut chips, mushy peas and tartare sauce</p>\r\n",
              "categoryCode": "571d0cbd-fc66-481f-bcd0-2f9e928e78c0",
              "itemCode": "17e8fef2-f44d-4ff3-ad1b-1ea47aff4e44",
              "printEnabled": false,
              "emailSharingEnable": false,
              "qrCodeEnabled": false,
              "promo": false,
              "directContentType": null,
              "availabilityPeriod": null,
              "attributes": [],
              "availabilityPeriods": [],
              "relatedCategoryItemCodes": [],
              "modifiers": [],
              "analyticsTag": null,
              "templateTag": null,
              "buttons": []
            },
            {
              "code": "1638de4b-cdf0-4226-beb4-dc9a664c3ed3",
              "price": 19,
              "imageUrl": "https://irisv4sandboxasstore.blob.core.windows.net/fileresources/public/iris/heddon/hhr/pieandmasha0b9135116d64d94b170f013cd13fdac.jpg",
              "directContentParameter": null,
              "type": "Product",
              "name": "Pie & Mash",
              "shortDescription": null,
              "longDescription": "<p>Classic short-crust pie served with creamy mashed potatoes and rich gravy</p>\r\n",
              "categoryCode": "571d0cbd-fc66-481f-bcd0-2f9e928e78c0",
              "itemCode": "6b94908f-b979-4bc8-aed9-8fd51a62977b",
              "printEnabled": false,
              "emailSharingEnable": false,
              "qrCodeEnabled": false,
              "promo": false,
              "directContentType": null,
              "availabilityPeriod": null,
              "attributes": [],
              "availabilityPeriods": [],
              "relatedCategoryItemCodes": [],
              "modifiers": [],
              "analyticsTag": null,
              "templateTag": null,
              "buttons": []
            },
            {
              "code": "2fab18f7-e9bd-428a-8293-f09dee41dacf",
              "price": 15,
              "imageUrl": "https://irisv4sandboxasstore.blob.core.windows.net/fileresources/public/iris/heddon/hhr/pepperonipizzae235f673a5994d209d6d7f3f1faf2769.jpg",
              "directContentParameter": null,
              "type": "Product",
              "name": "Pepperoni Pizza",
              "shortDescription": null,
              "longDescription": "<p>Wood-fired pizza with tomato, mozzarella, pepperoni and rocket</p>\r\n",
              "categoryCode": "571d0cbd-fc66-481f-bcd0-2f9e928e78c0",
              "itemCode": "e15a6cb1-8a1b-4bcf-916f-b2f038e1bb1e",
              "printEnabled": false,
              "emailSharingEnable": false,
              "qrCodeEnabled": false,
              "promo": false,
              "directContentType": null,
              "availabilityPeriod": null,
              "attributes": [],
              "availabilityPeriods": [],
              "relatedCategoryItemCodes": [],
              "modifiers": [],
              "analyticsTag": null,
              "templateTag": null,
              "buttons": []
            },
            {
              "code": "c1783897-3b8c-401d-921d-bd50d6d27bc7",
              "price": 15,
              "imageUrl": "https://irisv4sandboxasstore.blob.core.windows.net/fileresources/public/iris/heddon/hhr/spicypizza3db8ef1d1b244158ace29f17c4ae2af3.jpg",
              "directContentParameter": null,
              "type": "Product",
              "name": "Spicy Pizza",
              "shortDescription": null,
              "longDescription": "<p>Wood-fired pizza with tomato, mozzarella, roasted tomatoes, fresh chillis and rocket</p>\r\n",
              "categoryCode": "571d0cbd-fc66-481f-bcd0-2f9e928e78c0",
              "itemCode": "dbcfed34-c8af-4f62-8947-54b1ec029644",
              "printEnabled": false,
              "emailSharingEnable": false,
              "qrCodeEnabled": false,
              "promo": false,
              "directContentType": null,
              "availabilityPeriod": null,
              "attributes": [],
              "availabilityPeriods": [],
              "relatedCategoryItemCodes": [],
              "modifiers": [],
              "analyticsTag": null,
              "templateTag": null,
              "buttons": []
            },
            {
              "code": "239f6c45-2e2a-4c76-96b1-2bc85347d169",
              "price": 14,
              "imageUrl": "https://irisv4sandboxasstore.blob.core.windows.net/fileresources/public/iris/heddon/hhr/rocketpizza821ae68e3b894df78277cc0296ae0759.jpg",
              "directContentParameter": null,
              "type": "Product",
              "name": "Rocket Pizza",
              "shortDescription": null,
              "longDescription": "<p>Wood-fired pizza with tomato, mozzarella, roasted peppers and rocket</p>\r\n",
              "categoryCode": "571d0cbd-fc66-481f-bcd0-2f9e928e78c0",
              "itemCode": "f0aad4b3-f712-4e66-abd9-8c0fbcfd4754",
              "printEnabled": false,
              "emailSharingEnable": false,
              "qrCodeEnabled": false,
              "promo": false,
              "directContentType": null,
              "availabilityPeriod": null,
              "attributes": [],
              "availabilityPeriods": [],
              "relatedCategoryItemCodes": [],
              "modifiers": [],
              "analyticsTag": null,
              "templateTag": null,
              "buttons": []
            },
            {
              "code": "0cebd235-6568-43c3-96d6-7c0358dd8a3d",
              "price": 14,
              "imageUrl": "https://irisv4sandboxasstore.blob.core.windows.net/fileresources/public/iris/heddon/hhr/hamandpineapplepizza8c19c8cf14ad452aa2075701706264de.jpg",
              "directContentParameter": null,
              "type": "Product",
              "name": "Pineapple Pizza",
              "shortDescription": null,
              "longDescription": "<p>Wood-fired pizza with tomato, mozzarella, roasted peppers and pineapple</p>\r\n",
              "categoryCode": "571d0cbd-fc66-481f-bcd0-2f9e928e78c0",
              "itemCode": "84f51104-cf92-453a-aac8-9a713dbb07f6",
              "printEnabled": false,
              "emailSharingEnable": false,
              "qrCodeEnabled": false,
              "promo": false,
              "directContentType": null,
              "availabilityPeriod": null,
              "attributes": [],
              "availabilityPeriods": [],
              "relatedCategoryItemCodes": [],
              "modifiers": [],
              "analyticsTag": null,
              "templateTag": null,
              "buttons": []
            },
            {
              "code": "eff34939-842f-49de-9907-ed2eedfaf295",
              "price": 10,
              "imageUrl": "https://irisv4sandboxasstore.blob.core.windows.net/fileresources/public/iris/heddon/hhr/kidsfishandchipsa2112faf88244e588ffaf4e763463fd5.jpg",
              "directContentParameter": null,
              "type": "Product",
              "name": "Fish & Chips",
              "shortDescription": null,
              "longDescription": "<p>Fresh cod fillet lightly breaded with home-made chips and peas</p>\r\n",
              "categoryCode": "571d0cbd-fc66-481f-bcd0-2f9e928e78c0",
              "itemCode": "c1212e49-d17d-4043-ad1f-b3b454c59c1a",
              "printEnabled": false,
              "emailSharingEnable": false,
              "qrCodeEnabled": false,
              "promo": false,
              "directContentType": null,
              "availabilityPeriod": null,
              "attributes": [],
              "availabilityPeriods": [],
              "relatedCategoryItemCodes": [],
              "modifiers": [],
              "analyticsTag": null,
              "templateTag": null,
              "buttons": []
            }
          ]

const slots = {
  cookingOptions: {
    name: 'cookingOptions',
    value: 'Rare'
  },
  mainsOptions: {
    name: 'mainsOptions',
    value: 'Flat Iron Steak'
  }
}

export default { items, slots }
